version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto/"
phases:
  install:
    commands:
      - yum update; yum install -y java-17-amazon-corretto-jdk
      - update-alternatives --auto javac
      - update-alternatives --auto java
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'