version: 0.2

phases:
  install:
    commands:
      - yum update; yum -y install java-17-amazon-corretto-devel
      - update-alternatives --auto javac
      - update-alternatives --auto java
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - '**/*'