version: '2'

services:
  app:
    image: 'game-hub-backend.jar:latest'
    build:
      context: .
    container_name: spring_boot_container
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=ubuntu
  redis:
    image: 'redis:latest'
    container_name: redis_container
    restart: always
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin4_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=chrisleebed@gamil.com
      - PGADMIN_DEFAULT_PASSWORD=ubuntu
    ports:
      - "5555:80"
    depends_on:
      - db
#get postgres port:
#docker ps
#docker inspect {postgres_container_id} | grep IPAddress


#create the docker app
#docker-compose up