cloud:
  aws:
    credentials:
      access-key: AKIAVEOS2D2PBD757IEZ
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: gamehubimage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080